jenkins:
  authorizationStrategy:
    projectMatrix:
      permissions:
      - "GROUP:Agent/Build:authenticated"
      - "GROUP:Agent/Configure:authenticated"
      - "GROUP:Agent/Connect:authenticated"
      - "GROUP:Agent/Create:authenticated"
      - "GROUP:Agent/Delete:authenticated"
      - "GROUP:Agent/Disconnect:authenticated"
      - "GROUP:Credentials/Create:authenticated"
      - "GROUP:Credentials/Delete:authenticated"
      - "GROUP:Credentials/ManageDomains:authenticated"
      - "GROUP:Credentials/Update:authenticated"
      - "GROUP:Credentials/View:authenticated"
      - "GROUP:Job Config History/DeleteEntry:authenticated"
      - "GROUP:Job/Build:authenticated"
      - "GROUP:Job/Cancel:authenticated"
      - "GROUP:Job/Configure:authenticated"
      - "GROUP:Job/Create:authenticated"
      - "GROUP:Job/Delete:authenticated"
      - "GROUP:Job/Discover:authenticated"
      - "GROUP:Job/Move:authenticated"
      - "GROUP:Job/Read:authenticated"
      - "GROUP:Job/Workspace:authenticated"
      - "GROUP:Overall/Administer:authenticated"
      - "GROUP:Overall/Read:authenticated"
      - "GROUP:Run/Delete:authenticated"
      - "GROUP:Run/Replay:authenticated"
      - "GROUP:Run/Update:authenticated"
      - "GROUP:SCM/Tag:authenticated"
      - "GROUP:View/Configure:authenticated"
      - "GROUP:View/Create:authenticated"
      - "GROUP:View/Delete:authenticated"
      - "GROUP:View/Read:authenticated"
      - "USER:Agent/Build:anonymous"
      - "USER:Agent/Connect:anonymous"
      - "USER:Agent/Disconnect:anonymous"
      - "USER:Job/Build:anonymous"
      - "USER:Job/Cancel:anonymous"
      - "USER:Job/Discover:anonymous"
      - "USER:Job/Read:anonymous"
      - "USER:Overall/Read:anonymous"
      - "USER:Run/Replay:anonymous"
      - "USER:Run/Update:anonymous"
      - "USER:View/Read:anonymous"
  # securityRealm:
  #   github:
  #     clientID: "${GH_CLIENT_ID}"
  #     clientSecret: "${GH_CLIENT_SECRET}"
  #     githubApiUri: "https://api.github.com"
  #     githubWebUri: "https://github.com"
  #     oauthScopes: "read:org"
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
      - id: "${JENKINS_ADMIN_ID}"
        password: "${JENKINS_ADMIN_PASSWORD}"
  markupFormatter: "markdownFormatter"
  mode: EXCLUSIVE
  numExecutors: 0
unclassified:
  jobConfigHistory:
    maxHistoryEntries: "10"
  timestamper:
    allPipelines: false
    elapsedTimeFormat: "'<b>'HH:mm:ss.S'</b> '"
    systemTimeFormat: "'<b>'HH:mm:ss'</b> '"
