version: "3.9"

services:
  jenkins-master:
    build:
      context: ./jenkins-master
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./master_data_store:/var/jenkins_home
      - ./jenkins-master/config/jenkins.yaml:/config/jenkins.yaml:ro
    env_file:
      - ./jenkins-master/.env
    restart: unless-stopped

networks:
  default:
    name: jenkins-network

