version: "3.9"

services:
  # slave-ssh:
  #   build:
  #     context: ./slave-ssh_host_docker
  #     dockerfile: ./Dockerfile
  #     args:
  #       - DOCKERID=${DOCKERID}
  #       - ARCH=${ARCH}
  #       - DOCKER_VERSION=${DOCKER_VERSION}
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   env_file:
  #     - ./slave-ssh_host_docker/jenkins-agent.env
  #   restart: unless-stopped

  slave-golang:
    build:
      context: ./slave-golang
      dockerfile: ./Dockerfile
      args:
        - USER=jenkins
    environment:
      - JENKINS_URL=http://jenkins-master:8080
    env_file:
      - ./slave-golang/jenkins-agent.env
    restart: unless-stopped

networks:
  default:
    name: jenkins-network
    external: true

